default_install_hook_types: [pre-commit, post-checkout, post-merge]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: .*\.svg
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
        args: ["-C", "./backend"]
      - id: poetry-lock
        args: ["-C", "./backend", "--no-update"]
      - id: poetry-install
        args: ["-C", "./backend", "--sync", "--with=dev", "--no-root"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: ["backend", "--fix", "--exit-non-zero-on-fix"]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.351
    hooks:
      - id: pyright
        args:
          - "--project"
          - "backend"
        files: "backend"

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.9.2
    hooks:
      - id: markdownlint-cli2
